export const AUDIT_ACTIONS = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  REGISTER: "REGISTER",
  MEAL_CAPTURE: "MEAL_CAPTURE",
  CHAT_MESSAGE: "CHAT_MESSAGE",
  PROFILE_UPDATE: "PROFILE_UPDATE",
  AI_AGENT_CALL: "AI_AGENT_CALL",
  TEXT2SQL_QUERY: "TEXT2SQL_QUERY",
  ADMIN_USER_UPDATE: "ADMIN_USER_UPDATE",
  ADMIN_USER_DELETE: "ADMIN_USER_DELETE",
  ADMIN_USER_ROLE_CHANGE: "ADMIN_USER_ROLE_CHANGE",
  ADMIN_VIEW_USER_DETAIL: "ADMIN_VIEW_USER_DETAIL",
  ADMIN_VIEW_LOGS: "ADMIN_VIEW_LOGS",
  SYSTEM_ERROR: "SYSTEM_ERROR",
} as const;

export const REDIS_AUDIT_KEY = "audit:recent";
export const REDIS_CHAT_PREFIX = "chat:session:";
export const AUDIT_CACHE_TTL_SECONDS = 48 * 60 * 60;
export const AUDIT_CACHE_MAX_ENTRIES = 500;
